mysite/api/urls.py
from django.urls import path

from .views import *

app_name = 'api'

urlpatterns = [
    path('product_list', ProductsApiView.as_view(), name='product_list_api'),
    path('product_list/<int:cat_id>', CatApiView.as_view(), name='product_list_by_cat_api'),
    path('product_list/<int:cat_id>/<int:subcat_id>', SubCatApiView.as_view(), name='product_list_by_subcat_api'),
    path('product_list/<int:cat_id>/<int:subcat_id>/<int:pr_id>', ProductApiView.as_view(), name='product_api'),
    path('cart', CartApiView.as_view(), name='cart'),
    path('cart/add', AddOrderToCart.as_view(), name='cart_add'),
    path('product_list/<int:cat_id>/<int:subcat_id>/<int:pr_id>/add', ProductAddApiView.as_view(),
         name='product_add_api'),
    path('product_list/<int:cat_id>/<int:subcat_id>/<int:pr_id>/del', ProductDelApiView.as_view(),
         name='product_del_api'),
]

mysite/cart/urls.py
from django.urls import path
from .views import *

app_name = 'cart'

urlpatterns = [
    path('', cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', cart_add, name='cart_add'),
    path('remove/<int:product_id>/', cart_remove, name='cart_remove'),
]

mysite/mysite/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from mysite import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/v1/', include('api.urls', namespace='api')),
    path('orders/', include('orders.urls', namespace='orders')),  # регистрируем все маршруты приложения orders
    path('cart/', include('cart.urls', namespace='cart')),  # регистрируем все маршруты приложения cart
    path('shop/', include('shop.urls', namespace='shop'))  # регистрируем все маршруты приложения shop
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/shop/urls.py
from django.urls import path

from .views import *

app_name = 'shop'
urlpatterns = [
    path('', product_list, name='product_list'),
    path('<slug:category_slug>/', product_list, name='product_list_by_category'),
    path('<slug:category_slug>/<slug:subcategory_slug>', product_list, name='product_list_by_subcategory'),
    path('<slug:category_slug>/<slug:subcategory_slug>/<slug:product_slug>', product_detail, name='product_detail'),
]

mysite/shop/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=100, db_index=True, verbose_name='Название')
    slug = models.SlugField(max_length=100, unique=True, verbose_name='Слаг')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Категория'  # название в админ-панели
        verbose_name_plural = 'Категории'  # для множественного числа
        ordering = ['name']   # сортировка по имени в админ-панели

    # формирование ссылок с переменными адресами согласно правилу в urls.py
    def get_absolute_url(self):
        return reverse('shop:product_list_by_category', kwargs={'category_slug': self.slug})


class SubCategory(models.Model):
    category = models.ForeignKey(Category, related_name='subcategories',
                                    on_delete=models.CASCADE, verbose_name='Категории')
    name = models.CharField(max_length=100, db_index=True, verbose_name='Название')
    slug = models.SlugField(max_length=100, unique=True, verbose_name='Слаг')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Подкатегория'  # название в админ-панели
        verbose_name_plural = 'Подкатегории'  # для множественного числа
        ordering = ['name']  # сортировка по имени в админ-панели

    # формирование ссылок с переменными адресами согласно правилу в urls.py
    def get_absolute_url(self):
        return reverse('shop:product_list_by_subcategory', kwargs={'subcategory_slug': self.slug,
                                                                   'category_slug': self.category.slug})


class Product(models.Model):
    subcategory = models.ForeignKey(SubCategory, related_name='products',
                                 on_delete=models.CASCADE, verbose_name='Подкатегории')

    name = models.CharField(max_length=100, db_index=True, verbose_name='Название')
    slug = models.SlugField(max_length=100, unique=True, verbose_name='Слаг')
    description = models.TextField(max_length=1000, verbose_name='Описание')
    photo = models.ImageField(upload_to="product/%Y/%m/%d/", blank=True, verbose_name='Фото')
    price = models.DecimalField(max_digits=8, decimal_places=2, verbose_name='Цена')
    available = models.BooleanField(default=True, verbose_name='Наличие')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'
        ordering = ['name']

    def get_absolute_url(self):
        return reverse('shop:product_detail', kwargs={'product_slug': self.slug,
                                                      'subcategory_slug': self.subcategory.slug,
                                                      'category_slug': self.subcategory.category.slug})

mysite/shop/views.py
from django.shortcuts import render, get_object_or_404
from cart.forms import CartAddProductForm
from .models import Category, Product, SubCategory


def product_list(request, category_slug=None, subcategory_slug=None):
    category = None
    subcategory = None
    subcategories = None
    categories = Category.objects.all()     # вывод всех объектов
    products = Product.objects.filter(available=True)

    if category_slug:       # вывод объектов по категории
        category = get_object_or_404(Category, slug=category_slug)
        subcategories = SubCategory.objects.filter(category=category)
        products = products.filter(subcategory__in=subcategories)

        if subcategory_slug:    # вывод объектов по подкатегории
            subcategory = get_object_or_404(SubCategory, slug=subcategory_slug)
            products = products.filter(subcategory=subcategory)

    param = {'category': category, 'categories': categories, 'subcategories': subcategories,
             'subcategory': subcategory, 'products': products}

    return render(request, 'shop/list.html', context=param)


def product_detail(request, product_slug, category_slug, subcategory_slug):
    product = get_object_or_404(Product, slug=product_slug, available=True)
    form = CartAddProductForm()
    return render(request, 'shop/detail.html', {'product': product, 'form': form})

mysite/shop/templates/shop/base.html
{% load static %}

<!DOCTYPE html>
    <html>
        <head>
        <meta charset="utf-8" />
            <title>
                {% block title %}
                Мой магазин
                {% endblock %}
            </title>
                <link href="{% static 'css/base.css' %}" rel="stylesheet">
        </head>
        <body>
            <div id="header">
                <a href="{% url 'shop:product_list' %}">Мой магазин</a>
            </div>
            <div id="subheader">
                <div class="cart">
                {% with total_items=cart|length %}
                    {% if cart|length > 0 %}
                        Ваша корзина:
                    <a href="{% url 'cart:cart_detail' %}">
                        {{ total_items }} шт, RUB {{ cart.get_total_price }}
                    </a>
                    {% else %}
                    Ваша корзина пустая
                    {% endif %}
                {% endwith %}
                </div>
            </div>
            <div id="content">
                {% block content %}
                {% endblock %}
            </div>
        </body>
    </html>

mysite/shop/templates/shop/detail.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
{{ product.name }}
{% endblock %}
{% block content %}
<div class="product-detail">
    <img src="{% if product.photo %}{{ product.photo.url }}{% else %}
    {% static 'img/no_image.png' %}{% endif %}">
        <h1>{{ product.name }}</h1>
        <h2>
            <a href="{{ product.category.get_absolute_url }}">{{product.category}}</a>
        </h2>
        <p class="price">RUB {{ product.price }}</p>
        <form action="{% url 'cart:cart_add' product.id %}" method="post">
            {{ form }}
            {% csrf_token %}
            <input type="submit" value="Добавить в корзину">
        </form>
</div>
<div class="product-detail-des">
    {{ product.description|linebreaks }}
</div>
{% endblock %}

mysite/shop/templates/shop/list.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
{% if category %}{{ category.name }}{% else %}Товары{% endif %}
{% endblock %}
{% block content %}
<div id="sidebar">
    <h3>Категория</h3>
        <ul>
            <li {% if not category %} class="selected" {% endif %}>
            <a href="{% url 'shop:product_list' %}">Все</a>
            </li>
            {% for c in categories %}
            <li {% if category.slug == c.slug %} class="selected" {% endif %}>
                <a href="{{ c.get_absolute_url }}">{{ c.name }}</a><br>
                {% if category.slug == c.slug %}
                <ul>
                    {% for s in subcategories %}
                    <li {% if subcategory.slug == s.slug %} style="background:#88c8f2; border-radius:4px;" {% endif %}>
                        <a href ="{{ s.get_absolute_url }}"> {{ s.name }}</a>
                    </li>
                    {% endfor %}
                </ul>
                {% endif %}
            </li>
            {% endfor %}
        </ul>
</div>
<div id="main" class="product-list">
    <h1 style="color:#88c8f2;">{% if category and not subcategory%}{{ category.name }}
        {% elif subcategory%}{{ category.name }} > {{ subcategory.name }}
        {% else %}Товар
        {% endif %}</h1>
    {% for product in products %}
    <div class="item">
        <a href="{{ product.get_absolute_url }}">
            <img src="{% if product.photo %}{{ product.photo.url }}{%else %}{% static 'img/no_image.png' %}{% endif %}">
        </a><br>
        <a href="{{ product.get_absolute_url }}">{{ product.name }}</a>
        <br>
        RUB {{ product.price }}
    </div>
{% endfor %}
</div>
{% endblock %}